// flow-typed signature: 3575b0a6b2939d9aeafaa7f66d5be624
// flow-typed version: <<STUB>>/react-storybook-decorator-background_v1.0.5/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-storybook-decorator-background'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-storybook-decorator-background' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-storybook-decorator-background/lib/index' {
  declare module.exports: any;
}

declare module 'react-storybook-decorator-background/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-storybook-decorator-background/lib/index.js' {
  declare module.exports: $Exports<'react-storybook-decorator-background/lib/index'>;
}
declare module 'react-storybook-decorator-background/src/index.jsx' {
  declare module.exports: $Exports<'react-storybook-decorator-background/src/index'>;
}
