// flow-typed signature: d9b41296fb34b7951a95c14ebe6aa9c3
// flow-typed version: <<STUB>>/storybook-addon-scissors_v2.0.4/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-scissors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-scissors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-scissors/build/devices' {
  declare module.exports: any;
}

declare module 'storybook-addon-scissors/build/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-scissors/build/devices.js' {
  declare module.exports: $Exports<'storybook-addon-scissors/build/devices'>;
}
declare module 'storybook-addon-scissors/build/register.js' {
  declare module.exports: $Exports<'storybook-addon-scissors/build/register'>;
}
