// flow-typed signature: 62b93d6fddef126175a40a63adaa7c1f
// flow-typed version: <<STUB>>/storybook-addon-smart-knobs_v0.3.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-smart-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-smart-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-smart-knobs/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/example/stories/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/example/stories/SmartKnobedComponent' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/example/stories/SmartKnobedComponentMissingProps' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/src/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/storybook-static/static/manager.bundle' {
  declare module.exports: any;
}

declare module 'storybook-addon-smart-knobs/storybook-static/static/preview.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-smart-knobs/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/dist/index'>;
}
declare module 'storybook-addon-smart-knobs/example/stories/index.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/example/stories/index'>;
}
declare module 'storybook-addon-smart-knobs/example/stories/SmartKnobedComponent.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/example/stories/SmartKnobedComponent'>;
}
declare module 'storybook-addon-smart-knobs/example/stories/SmartKnobedComponentMissingProps.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/example/stories/SmartKnobedComponentMissingProps'>;
}
declare module 'storybook-addon-smart-knobs/src/index.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/src/index'>;
}
declare module 'storybook-addon-smart-knobs/storybook-static/static/manager.bundle.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/storybook-static/static/manager.bundle'>;
}
declare module 'storybook-addon-smart-knobs/storybook-static/static/preview.bundle.js' {
  declare module.exports: $Exports<'storybook-addon-smart-knobs/storybook-static/static/preview.bundle'>;
}
